#ifndef MYmsgH
#define MYmsgH
#define WM_FORGE_GOTBLOCK (WM_USER+1)
#define WM_FORGE_MISSBLOCK (WM_USER+2)
#define WM_FORGE_SEVER_OFFLINE (WM_USER+3)
#define WM_FORGE_SEVER_ONLINE (WM_USER+4)
#define WM_VOTES_INCOMING (WM_USER+5)
#define WM_VOTES_REMOVE (WM_USER+6)
#define WM_BALANCE_INCOMING (WM_USER+7)
#define WM_BALANCE_SENDOUT (WM_USER+8)
#define WM_NODE_APPLY (WM_USER+101)
extern PACKAGE HWND MainFrmHand;
extern PACKAGE UnicodeString MAIN_PUBLIC_NODE;
extern PACKAGE UnicodeString TEST_PUBLIC_NODE;
extern PACKAGE UnicodeString TEST_USERNAME;
extern PACKAGE UnicodeString TEST_PKEY;
extern PACKAGE UnicodeString MAIN_USERNAME;
extern PACKAGE UnicodeString MAIN_PKEY;
#endif
