// Do not edit. This file is machine generated by the Resource DLL Wizard.

library libLiskApi;

{ITE} {RCFileType} {Win32\Release\libLiskApi_DRC.rc}

{$R 'Win32\Release\libLiskApi_DRC.res' 'Win32\Release\libLiskApi_DRC.rc'}

{$E ENU}

begin
end.
